"""
togaf_engine.py

What it does: Core TOGAF ADM engine that manages phases, dependencies,
             and artifact generation.

Dependencies: typing, models.phase, models.artifact
"""

from typing import Dict, List, Optional, Any
from datetime import datetime
import markdown

from ..models.phase import ADMPhase, PhaseRegistry
from ..models.artifact import Artifact
from ..services.bedrock import BedrockService
from ..services.storage import StorageService


class TOGAFEngine:
    """Core engine for TOGAF Architecture Development Method."""

    def __init__(self, bedrock: Optional[BedrockService] = None,
                 storage: Optional[StorageService] = None):
        self.bedrock = bedrock
        self.storage = storage
        self.phase_data: Dict[str, Dict[str, Any]] = {}  # project_id -> phase -> data

    def get_phase_form(self, phase: ADMPhase) -> Dict[str, str]:
        """Get form fields for a phase."""
        phase_def = PhaseRegistry.get(phase)
        return phase_def.form_fields if phase_def else {}

    def validate_phase_input(self, project_id: str, phase: ADMPhase,
                             completed_phases: List[str]) -> bool:
        """Check if phase dependencies are met."""
        deps = PhaseRegistry.get_dependencies(phase)
        return all(dep.value in completed_phases for dep in deps)

    def save_phase_data(self, project_id: str, phase: ADMPhase, data: Dict[str, Any]):
        """Save phase input data."""
        if project_id not in self.phase_data:
            self.phase_data[project_id] = {}
        self.phase_data[project_id][phase.value] = {
            'data': data,
            'saved_at': datetime.utcnow().isoformat()
        }

    def generate_artifact(self, project_id: str, phase: ADMPhase,
                          artifact_name: str, context: Dict[str, Any]) -> Artifact:
        """Generate an architecture artifact."""
        # Build context for generation
        context_with_project = {
            'project_id': project_id,
            'phase': phase.value,
            'artifact_name': artifact_name,
            **context
        }

        # Try Bedrock first
        content = None
        if self.bedrock and self.bedrock.is_available:
            content = self.bedrock.generate_artifact(
                phase.value, artifact_name, context_with_project
            )

        # Fallback to template
        if not content:
            content = self._generate_template(
                project_id, phase, artifact_name, context
            )

        # Create artifact
        artifact = Artifact(
            project_id=project_id,
            phase=phase.value,
            name=artifact_name,
            content=content
        )

        # Store if storage available
        if self.storage:
            location = self.storage.save_artifact(artifact.id, content)
            artifact.s3_key = location

        return artifact

    def _generate_template(self, project_id: str, phase: ADMPhase,
                           artifact_name: str, data: Dict[str, Any]) -> str:
        """Generate template-based artifact content."""
        project_name = data.get('project_name', 'Unnamed Project')

        return f"""# {artifact_name}

## Project: {project_name}
## Phase: {phase.value}
## Generated: {datetime.utcnow().isoformat()}

### Input Summary:
{json.dumps(data, indent=2)}

### Artifact Content:

This {artifact_name} has been generated based on the provided input.

**Key Decisions:**
- Based on stakeholder input, the following decisions were made...
- The architecture will prioritize scalability and security...
- Cloud-native approaches will be used where applicable...

**Next Steps:**
1. Review this artifact with stakeholders
2. Proceed to the next phase
3. Update the architecture repository

---
*This artifact was automatically generated by the TOGAF AI Orchestrator.*
"""

    def get_next_phases(self, completed_phases: List[str]) -> List[ADMPhase]:
        """Determine which phases can be started next."""
        next_phases = []
        for phase in ADMPhase:
            if phase.value not in completed_phases:
                deps = PhaseRegistry.get_dependencies(phase)
                if all(dep.value in completed_phases for dep in deps):
                    next_phases.append(phase)
        return next_phases